### ISSUE TITLE
unit tests for specific slots in domino objects

### ISSUE THREAD

**Issue by jmitchell81** [FertigLab/domino2#50]
Priority slots in the domino object for unit tests

Checks for result of create_domino:
- [ ] dom@linkages$complexes
- [ ] dom@linkages$rec_lig
- [ ] dom@linkages$tf_targets
- [ ] dom@clust_de
- [ ] dom@cor

Checks for result of build_domino
- [ ] dom@linkages$clust_tf
- [ ] dom@linkages$clust_rec
- [ ] dom@linkages$clust_tf_rec
- [ ] dom@linkages$clust_incoming_lig
- [ ] dom@linkages$tf_rec
- [ ] dom@cl_signaling_matrices
- [ ] dom@signaling

**Comment by dimalvovs** [comment]
done in [398d1f5](https://github.com/FertigLab/domino2/commit/398d1f5a41f04b28ae1ea04a29a7e7be7af8cdc6)
